language: ruby
cache: bundler
sudo: false
dist: trusty
rvm:
  - 2.4.0
services: mongodb
language: objective-c
addons:
  chrome: beta
before_install:
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
env:
  global:
    - METRICS_API_USERNAME="username"
    - METRICS_API_PASSWORD="password"
    - METRICS_API_TITLE='ODI Metrics'
    - METRICS_API_DESCRIPTION='This API contains a list of all metrics collected by the Open Data Institute since 2013'
    - METRICS_API_LICENSE_NAME='Creative Commons Attribution-ShareAlike'
    - METRICS_API_LICENSE_URL='https://creativecommons.org/licenses/by-sa/4.0/'
    - METRICS_API_PUBLISHER_NAME='Open Data Institute'
    - METRICS_API_PUBLISHER_URL='http://theodi.org'
    - METRICS_API_CERTIFICATE_URL='https://certificates.theodi.org/en/datasets/213482/certificate'